/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.projetoIntegrador.tela;

import br.com.projetoIntegrador.dao.CampeonatoDaoImpl;
import br.com.projetoIntegrador.dao.EquipeDaoImpl;
import br.com.projetoIntegrador.dao.ParticipanteDaoImpl;
import br.com.projetoIntegrador.entidade.Campeonato;
import br.com.projetoIntegrador.entidade.Equipe;
import br.com.projetoIntegrador.entidade.Participante;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author maria
 */
public class TelaPesquisa extends javax.swing.JFrame {

    private List<Campeonato> campeonatos;
    private List<Equipe> equipes;
    private List<Participante> participantes;
    private CampeonatoDaoImpl campeonatoDaoImpl;
    private  EquipeDaoImpl equipeDaoImpl;
    private ParticipanteDaoImpl participanteDaoImpl;
    private String nomePesquisado;

    /**
     * Creates new form TelaPesquisa
     */
    public TelaPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTituloPrincipal = new javax.swing.JLabel();
        lbPesquisa = new javax.swing.JLabel();
        varPesquisa = new javax.swing.JTextField();
        lbPesquisarEm = new javax.swing.JLabel();
        jComboBox = new javax.swing.JComboBox<>();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btExcluir = new javax.swing.JButton();
        btVoltaMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbTituloPrincipal.setFont(new java.awt.Font("Ink Free", 0, 50)); // NOI18N
        lbTituloPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTituloPrincipal.setText("Pesquisa");

        lbPesquisa.setFont(new java.awt.Font("Ink Free", 1, 16)); // NOI18N
        lbPesquisa.setForeground(new java.awt.Color(102, 102, 102));
        lbPesquisa.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPesquisa.setText("Pesquisa:");

        lbPesquisarEm.setFont(new java.awt.Font("Ink Free", 1, 16)); // NOI18N
        lbPesquisarEm.setForeground(new java.awt.Color(102, 102, 102));
        lbPesquisarEm.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbPesquisarEm.setText("Pesquisar em:");

        jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Campeonato", "Equipe", "Participante", " " }));

        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btExcluirActionPerformed(evt);
            }
        });

        btVoltaMenu.setText("Voltar ao menu");
        btVoltaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(lbPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbPesquisarEm)
                        .addGap(4, 4, 4)
                        .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(271, 271, 271)
                        .addComponent(lbTituloPrincipal))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(btExcluir)
                        .addGap(88, 88, 88)
                        .addComponent(btVoltaMenu)))
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(lbTituloPrincipal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPesquisa)
                    .addComponent(varPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPesquisarEm)
                    .addComponent(jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btExcluir)
                    .addComponent(btVoltaMenu))
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed

        nomePesquisado = varPesquisa.getText().trim();
        String grupoPesquisado = String.valueOf(jComboBox.getSelectedItem());
        if (grupoPesquisado.equals("Campeonato")) {
            try {
                preenchePesquisaCampeonato(nomePesquisado);
            } catch (SQLException ex) {
                System.out.println("Erro ao preencher equipe " + ex.getMessage());
            }
        };
        if (grupoPesquisado.equals("Equipe")) {
            try {
                preenchePesquisaEquipe(nomePesquisado);
            } catch (SQLException ex) {
                System.out.println("Erro ao preencher equipe " + ex.getMessage());
            }
        }
        if (grupoPesquisado.equals("Participante")) {
            try {
                preenchePesquisaParticipante(nomePesquisado);
            } catch (SQLException ex) {
                System.out.println("Erro ao preencher participante " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        nomePesquisado = varPesquisa.getText().trim();
        String grupoPesquisado = String.valueOf(jComboBox.getSelectedItem());
//        ModeloTabela modelo = new ModeloTabela();

        int linha = jTable1.getSelectedRow();
//        int[] colunas = jTable1.getSelectedColumns();
//        int indexLinha = jTable1.
        if (linha >= 0) {
            try {

                if (grupoPesquisado.equals("Campeonato")) {
                    int id = (int) jTable1.getValueAt(linha, 0);
                    excluiCampeonato(id);
                    campeonatos.remove(linha);
                    preenchePesquisaCampeonato(nomePesquisado);

                }

                if (grupoPesquisado.equals("Equipe")) {
                    equipes.remove(linha);
                    Equipe equipe = equipes.get(linha);
                    excluirEquipe(equipe.getId());
                    preenchePesquisaEquipe(nomePesquisado);

                }

                if (grupoPesquisado.equals("Participante")) {
                    participantes.remove(linha);
                    Participante participante = participantes.get(linha);
                    excluirParticipante(participante.getId());
                    preenchePesquisaParticipante(nomePesquisado);
                }
            } catch (SQLException ex) {
                System.out.println("Erro ao excluir " + ex.getMessage());
            }
        } else {
            System.out.println("Nenhuma linha selecionada.");
        }


    }//GEN-LAST:event_btExcluirActionPerformed

    private void btVoltaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltaMenuActionPerformed
        new TelaPrincipal().setVisible(true);
        dispose();
    }//GEN-LAST:event_btVoltaMenuActionPerformed

    //Metodos que apagam o objeto selecionado no banco chamando classes DaoImpl
    public void excluiCampeonato(int id) {
        equipes = equipeDaoImpl.pesquisarEquipesPorIdCampeonato(id);
        if(equipes != null){
             campeonatoDaoImpl.excluir(id);
        }else{
            System.out.println("O campeonato não pode ser excluido pois possue equipes, por favor exclua as equipes primeiro!");
        }
       
    }

    public void excluirEquipe(int id) throws SQLException {
       
        equipeDaoImpl.excluir(id);
    }

    public void excluirParticipante(int id) {
        
        participanteDaoImpl.excluir(id);
    }

    //Metodos que preenchem a tabela de acordo com o grupo escolhido na common box 
    public void preenchePesquisaCampeonato(String nomePesquisado) throws SQLException {

        CampeonatoDaoImpl campeonatoDaoImpl = new CampeonatoDaoImpl();
        campeonatos = campeonatoDaoImpl.pesquisarCampeonatoPorNome(nomePesquisado);//retorna todos os campeonatos que tenho

        String[] coluna = new String[]{"ID", "Campeonato", "Data", "Logradouro", "Bairro", "Cidade", "Estado", "Cep", "Complemento"};
        ArrayList dados = new ArrayList();
        for (Campeonato campeonato : campeonatos) {

            dados.add(new Object[]{
                campeonato.getId(),
                campeonato.getNomeCampeonato(),
                campeonato.getDataCampeonato(),
                campeonato.getEndereco().getLogradouro(),
                campeonato.getEndereco().getBairro(),
                campeonato.getEndereco().getCidade(),
                campeonato.getEndereco().getEstado(),
                campeonato.getEndereco().getCep(),
                campeonato.getEndereco().getComplemento()
            });

        }
        ModeloTabela modelo = new ModeloTabela(dados, coluna);
        jTable1.setModel(modelo);

    }

    public void preenchePesquisaEquipe(String nomePesquisado) throws SQLException {
        EquipeDaoImpl equipeDaoImpl = new EquipeDaoImpl();
        equipes = equipeDaoImpl.pesquisarEquipePorNomeEquipe(nomePesquisado);

        String[] coluna = new String[]{"ID", "Equipe", "Campeonato", "Data"};
        ArrayList dados = new ArrayList();

        for (Equipe equipe : equipes) {

            dados.add(new Object[]{
                equipe.getId(),
                equipe.getNome(),
                equipe.getCampeonato().getNomeCampeonato(),
                equipe.getCampeonato().getDataCampeonato()
            });
        }
        ModeloTabela modelo = new ModeloTabela(dados, coluna);
        jTable1.setModel(modelo);
    }

    public void preenchePesquisaParticipante(String nomePesquisado) throws SQLException {
        ParticipanteDaoImpl participanteDaoImpl = new ParticipanteDaoImpl();
        participantes = participanteDaoImpl.pesquisarParticipantesPorNome(nomePesquisado);

        String[] coluna = new String[]{"ID", "Nome", "CPF", "Telefone", "Equipe", "Logradouro", "Bairro", "Cidade", "Estado", "Cep", "Complemento"};
        ArrayList dados = new ArrayList();

        for (Participante participante : participantes) {
            dados.add(new Object[]{
                participante.getId(),
                participante.getNome(),
                participante.getCpf(),
                participante.getTelefone(),
                participante.getEquipe().getNome(),
                participante.getEndereco().getLogradouro(),
                participante.getEndereco().getBairro(),
                participante.getEndereco().getCidade(),
                participante.getEndereco().getEstado(),
                participante.getEndereco().getCep(),
                participante.getEndereco().getComplemento()
            }
            );
        }
        ModeloTabela modelo = new ModeloTabela(dados, coluna);
        jTable1.setModel(modelo);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btPesquisar;
    private javax.swing.JButton btVoltaMenu;
    private javax.swing.JComboBox<String> jComboBox;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lbPesquisa;
    private javax.swing.JLabel lbPesquisarEm;
    private javax.swing.JLabel lbTituloPrincipal;
    private javax.swing.JTextField varPesquisa;
    // End of variables declaration//GEN-END:variables
}
